--   λ(s : Type)
-- →   { eval =
--         ./eval s
--     , exec =
--         ./exec s
--     , get =
--         ./get s
--     , modify =
--         ./modify s
--     , put =
--         ./put s
--     , withState =
--         ./withState s
--     }
--   ∧ ./../Monad/package.dhall
--     Type
--     ./../Function/Type
--     ./../Function/semigroupoid
--     (./Type s)
--     (./monad s)
<>
